# 1

In [1]:
import numpy as np

In [2]:
arr = np.array([[4,55,6,77]], np.int64)

In [3]:
arr

array([[ 4, 55,  6, 77]], dtype=int64)

In [4]:
arr.shape

(1, 4)

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.size

4

In [7]:
arr[0,2]

6

In [8]:
arr[0,2] = 66

In [9]:
arr

array([[ 4, 55, 66, 77]], dtype=int64)

# 2


In [10]:
zeros = np.zeros((2,5))

In [11]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
ones = np.ones((2,5))

In [13]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
eyes = np.eye(4)

In [15]:
eyes

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
dig = np.diag([3,4,5,6])

In [17]:
dig

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [18]:
np.diag(dig)

array([3, 4, 5, 6])

In [19]:
np.random.randint(1,10,3)

array([3, 6, 4])

In [20]:
np.random.seed(2)
np.random.randint(1,10,3)

array([9, 9, 7])

In [21]:
np.random.rand(2,4)

array([[0.94773061, 0.4847491 , 0.32053644, 0.15442667],
       [0.69886269, 0.11995054, 0.48517591, 0.63273773]])

In [22]:
arng = np.arange(15)

In [23]:
arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arng = arng.reshape(5,3)

In [25]:
arng

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
arng = arng.ravel()

In [27]:
arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
lspace = np.linspace(1,10,5)

In [29]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [30]:
emp = np.empty((2,3))

In [31]:
emp

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
emp_like = np.empty_like(lspace)

In [33]:
emp_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [34]:
ide = np.identity(3)

In [35]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
l = [[1,2,3],[4,5,6],[7,1,0]]

In [37]:
arr = np.array(l)

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [39]:
arr.sum(axis=0)

array([12,  8,  9])

In [40]:
arr.sum(axis=1)

array([ 6, 15,  8])

# attribute and method

*transpose*

In [41]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [42]:
arr.flat

In [43]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [44]:
arr.ndim

2

In [45]:
arr.nbytes

36

In [46]:
one = np.array([1,3,55,2,77])

In [47]:
one.argmax()

4

In [48]:
one.argmin()

0

In [49]:
one.argsort()

array([0, 3, 1, 2, 4], dtype=int64)

In [50]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [52]:
arr.argmax()

6

In [53]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [54]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [55]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [56]:
arr2 = np.array([[0,1,0],
                [0,0,1],
                [1,0,0]])

In [57]:
arr + arr2

array([[1, 3, 3],
       [4, 5, 7],
       [8, 1, 0]])

In [58]:
arr * arr2

array([[0, 2, 0],
       [0, 0, 6],
       [7, 0, 0]])

In [59]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [60]:
arr.max()

7

In [61]:
arr.min()

0

In [62]:
arr.sum()

29

In [63]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [64]:
np.count_nonzero(arr)

8

In [65]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [66]:
import sys

In [67]:
py_arr = [1,2,3]

In [68]:
np_arr = np.array(py_arr)

In [69]:
sys.getsizeof(1) * len(py_arr)

84

In [70]:
np_arr.itemsize * np_arr.size

12

In [71]:
arr.tolist()

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [72]:
one

array([ 1,  3, 55,  2, 77])

In [73]:
one[2:4]

array([55,  2])

In [74]:
one[2:4] = 0

In [75]:
one

array([ 1,  3,  0,  0, 77])

In [76]:
one[0:2].copy()

array([1, 3])

In [77]:
one[0:2] = 9

In [78]:
one

array([ 9,  9,  0,  0, 77])

In [79]:
arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
arng>10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True])

In [81]:
arng[arng>10]

array([11, 12, 13, 14])

In [82]:
arng[arng%2 ==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [83]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [84]:
arr+1

array([[2, 3, 4],
       [5, 6, 7],
       [8, 2, 1]])

In [85]:
arr**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343,   1,   0]], dtype=int32)

In [86]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [87]:
np.array([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [88]:
np.random.shuffle(arr)

In [89]:
arr

array([[7, 1, 0],
       [4, 5, 6],
       [1, 2, 3]])

In [90]:
np.unique(arr).size

8

In [91]:
arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
one

array([ 9,  9,  0,  0, 77])

In [93]:
np.hstack((one,arng))

array([ 9,  9,  0,  0, 77,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14])

In [94]:
np.vstack((one,one))

array([[ 9,  9,  0,  0, 77],
       [ 9,  9,  0,  0, 77]])

In [95]:
[i**2 for i in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [96]:
%timeit [i**2 for i in range(1,11)]

3.09 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [97]:
np.arange(1,11)**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [98]:
%timeit np.arange(1,11)**2

1.53 µs ± 63.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [99]:
arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [100]:
np.searchsorted(arng,11)

11

indexing and selection

sum